# file = filename without .md, slug = URL path, heading = display title
files:
  - file: "01_one"
    slug: "introduction-to-html"
    heading: Introduction to HTML
  - file: "02_two"
    slug: "html-elements"
    heading: HTML Elements
  - file: "03_three"
    slug: "html-attributes"
    heading: HTML Attributes
  - file: "04_four"
    slug: "html-headings"
    heading: HTML Headings
  - file: "05_five"
    slug: "html-paragraphs"
    heading: HTML Paragraphs
